# docker-compose.yml

version: '3.8'

services:
  decrypt_api:
    build: .
    image: p0lcatha/decrypt-test:latest
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:decrypt_app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgres://postgres:n3clFrUr1sLsw5W6eFO&@db:5432/freqlangdb
    depends_on:
      - db
  db:
    #image: postgres:13-alpine
    image: p0lcatha/postgres-config
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=n3clFrUr1sLsw5W6eFO&
      - POSTGRES_DB=freqlangdb

volumes:
  postgres_data: